services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idyie-llm-api
    ports:
      - "$PORT:$PORT"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
    command: python run.py

networks:
  default:
    driver: bridge
  idyie-network:
    external: true
    name: idyie-network
