services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idyie-llm-application
    ports:
      - "$PORT:$PORT"
    environment:
      FLASK_ENV: $FLASK_ENV
      IDYIE_API_URL: $IDYIE_API_URL
    networks:
      - idyie-network
    volumes:
      - .:/app
    command: python run.py

networks:
  default:
    driver: bridge
  idyie-network:
    external: true
    name: idyie-network
