name: Lint, Build, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update -qy
          apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run flake8
        run: flake8 .

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: lint
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build
        env:
          PORT: ${{ secrets.PORT }}

  test:
    name: Run unittest
    runs-on: ubuntu-latest
    needs: build
    env:
      PORT: ${{ secrets.PORT }}
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Docker network
        run: docker network create idyie-network || true

      - name: Setup Docker Compose
        run: docker compose up -d

      - name: Run unittest
        run: docker compose exec api python -m unittest
